# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 18:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_add_course_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='backinginstance',
            name='access_token',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='backinginstance',
            name='access_token_expiration',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='backinginstance',
            name='grant_token',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='backinginstance',
            name='oauth_client_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='backinginstance',
            name='oauth_client_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='backinginstance',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='backinginstance',
            name='username',
            field=models.CharField(blank=True, help_text='Username the backing oauth user is attached to. This is used to request course structure and MUST be a staff member of the course.', max_length=30, null=True),
        ),
    ]
