# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_more_oauth_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ('course_id', 'order'), 'permissions': (('edit_own_price', 'Can edit the price of a module'),)},
        ),
        migrations.AddField(
            model_name='course',
            name='edx_course_id',
            field=models.TextField(help_text='course locator from edx', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='module',
            name='locator_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
