# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 13:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_ccxcon_course_module_fields'),
        ('portal', '0011_more_oauth_fields'),
    ]

    operations = [
    ]
