# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='edx_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.BackingInstance'),
        ),
    ]
