db:
  image: postgres
  ports:
    - "5432"
web:
  build: .
  command: >
    /bin/bash -c '
    sleep 3 &&
    python manage.py migrate &&
    ./with_host.sh python manage.py runserver 0.0.0.0:8075'
  volumes:
    - .:/src
  environment:
    DEBUG: 'True'
    PORT: 8075
    DATABASE_URL: postgres://postgres@db:5432/postgres
    PORTAL_DB_DISABLE_SSL: 'True'
    CCXCON_API: http://private-anon-388fdf8b0-ccxcon.apiary-mock.com/api/
  ports:
    - "8075:8075"
  links:
    - db
watch:
  image: teachersportal_web
  command: >
    /bin/bash -c '
    npm cache clean &&
    npm install --production --no-bin-links &&
    npm rebuild node-sass &&
    echo Finished npm install &&
    node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js --content-base ./static --host 0.0.0.0 --port 8076 --progress --hot --inline'
  ports:
    - "8076:8076"
  volumes:
    - .:/src
