db:
  image: postgres
  ports:
    - "5432"

redis:
  image: redis
  ports:
    - "6379"

web:
  build: .
  command: >
    /bin/bash -c '
    sleep 3 &&
    python manage.py migrate &&
    ./with_host.sh python manage.py runsslserver 0.0.0.0:8075 --certificate=cert/fullchain.pem --key=cert/privkey.pem'
  volumes:
    - .:/src
  environment:
    DEBUG: 'True'
    NODE_ENV: 'development'
    PORT: 8075
    DATABASE_URL: postgres://postgres@db:5432/postgres
    PORTAL_DB_DISABLE_SSL: 'True'
    PORTAL_USE_WEBPACK_DEV_SERVER: 'True'
    PORTAL_EMAIL_BACKEND: 'django.core.mail.backends.console.EmailBackend'
    PORTAL_SECURE_SSL_REDIRECT: 'True'
    STATUS_TOKEN: 'test-token'
    CELERY_ALWAYS_EAGER: 'False'
    CELERY_RESULT_BACKEND: redis://redis:6379/4
    BROKER_URL: redis://redis:6379/4
    COVERAGE_DIR: htmlcov
  env_file: .env
  ports:
    - "8075:8075"
  links:
    - db
    - redis

watch:
  image: teachersportal_web
  command: >
    /bin/bash -c '
    npm cache clean &&
    npm install --no-bin-links &&
    npm rebuild node-sass &&
    echo Finished npm install &&
    node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js --https --config webpack.config.dev.js -d --content-base ./static --host 0.0.0.0 --port 8076 --progress --inline --hot'
  ports:
    - "8076:8076"
  volumes:
    - .:/src
  environment:
    NODE_ENV: 'development'

celery:
  image: teachersportal_web
  command: >
    /bin/bash -c '
    sleep 3;
    celery -A teachersportal worker -l debug'
  volumes_from:
    - web
  environment:
    DEBUG: 'True'
    DJANGO_LOG_LEVEL: INFO
    DATABASE_URL: postgres://postgres@db:5432/postgres
    PORTAL_DB_DISABLE_SSL: 'True'
    BROKER_URL: redis://redis:6379/4
    CELERY_RESULT_BACKEND: redis://redis:6379/4
  extra_hosts:
    - "localhost.daplie.com:192.168.33.10"
  env_file: .env
  links:
    - db
    - redis
