db:
  image: postgres
  ports:
    - "5432"
web:
  build: .
  command: >
    /bin/bash -c '
    sleep 3 &&
    python manage.py migrate &&
    python manage.py runserver 0.0.0.0:$PORT'
  volumes:
    - .:/src
  environment:
    PORT: 8075
    DATABASE_URL: postgres://postgres@db:5432/postgres
  ports:
    - "8075:8075"
  links:
    - db
watch:
  image: teachersportal_web
  command: >
    /bin/bash -c '
    npm install --production --no-bin-links &&
    echo Finished npm install &&
    node ./node_modules/webpack/bin/webpack.js --watch'
  volumes:
    - .:/src
