db:
  image: postgres
  ports:
    - "5432"
web:
  build: .
  command: >
    /bin/bash -c '
    sleep 3 &&
    python manage.py migrate &&
    ./with_host.sh python manage.py runserver 0.0.0.0:8075'
  environment:
    DEBUG: 'False'
    NODE_ENV: 'production'
    PORT: 8075
    DATABASE_URL: postgres://postgres@db:5432/postgres
    PORTAL_DB_DISABLE_SSL: 'True'
    CCXCON_API: http://private-anon-388fdf8b0-ccxcon.apiary-mock.com/api/
    PORTAL_SECURE_SSL_REDIRECT: 'False'
  ports:
    - "8075:8075"
  links:
    - db
